### ISSUE TITLE
Errors importing statsd

### ISSUE THREAD

**Issue by morganlmarks** [miketheman/heroku-buildpack-datadog#11]
Deploying with the buildpack worked fine but when I ran the process that used statsd I got import errors because docker is not installed. 

2015-12-28T19:59:39.141210+00:00 heroku[api]: Scale to monitor=1, web=1 by user@example.com
2015-12-28T19:59:49.101389+00:00 heroku[monitor.1]: Starting process with command `python tools/monitor.py`
2015-12-28T19:59:51.380028+00:00 app[monitor.1]: Traceback (most recent call last):
2015-12-28T19:59:51.380050+00:00 app[monitor.1]:   File "/app/.apt/opt/datadog-agent/agent/dogstatsd.py", line 7, in <module>
2015-12-28T19:59:51.380055+00:00 app[monitor.1]:     from config import initialize_logging  # noqa
2015-12-28T19:59:51.380056+00:00 app[monitor.1]:   File "/app/.apt/opt/datadog-agent/agent/config.py", line 25, in <module>
2015-12-28T19:59:51.380082+00:00 app[monitor.1]:     from util import get_os, yLoader
2015-12-28T19:59:51.380086+00:00 app[monitor.1]:   File "/app/.apt/opt/datadog-agent/agent/util.py", line 34, in <module>
2015-12-28T19:59:51.380125+00:00 app[monitor.1]:     from utils.platform import Platform
2015-12-28T19:59:51.380129+00:00 app[monitor.1]:   File "/app/.apt/opt/datadog-agent/agent/utils/platform.py", line 5, in <module>
2015-12-28T19:59:51.380161+00:00 app[monitor.1]:     from utils.dockerutil import get_client
2015-12-28T19:59:51.380181+00:00 app[monitor.1]:   File "/app/.apt/opt/datadog-agent/agent/utils/dockerutil.py", line 5, in <module>
2015-12-28T19:59:51.380206+00:00 app[monitor.1]:     from docker import Client
2015-12-28T19:59:51.380231+00:00 app[monitor.1]: ImportError: No module named docker

I don't know why we would need to have docker installed. Any insights?

**Comment by miketheman** [comment]
@morganlmarks Is this still happening? If so, please reopen with details such as the current Agent package that is being installed. This can be seen in the deploy logs, something like:
```
remote: -----> Installing datadog-agent_1%3a5.8.0-1_amd64.deb
```
